plugins:
    - jekyll-remote-theme
remote_theme: chromatical/jekyll-materialdocs
title: BITS Voting DApp
description: Docs for the "BITS Voting DApp" project
copyright: C. Shri Akhil
menu_style: dropdown
mdl_colors: indigo-blue
